### PR TITLE
Fixed  Medium Issue (Python) #1523

### PR DESCRIPTION
**Pull request by SourabhRajput123**
## Pull Request Type

What kind of change does this PR introduce?

[x] Solved an issue/task
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:

## What is the current behavior?

The current behavior is the absence of a bubble sort function in the codebase.

Issue Number: N/A

## What is the new behavior?

The new behavior is the addition of a bubble sort function called `bubble_sort` that can sort an array of integers in ascending order.

## Other information

N/A

### CODE REVIEW

**Comment by SourabhRajput123** [comment]
Hello @nikohoffren,

I hope this message finds you well. I'm reaching out to seek your guidance regarding GitHub. As a newcomer to the platform, I find myself encountering challenges, particularly with regards to commits and pull requests. Specifically, I'm aiming to submit individual pull requests for each task I complete. However, I've noticed that when I make a commit while a pull request is open, the commit automatically becomes associated with that pull request.

I would greatly appreciate any insights or advice you could offer on how to address this issue.

Thank you for your time and assistance.

Warm regards,
@SourabhRajput123

**Comment by nikohoffren** [comment]
> Hello @nikohoffren,
> 
> I hope this message finds you well. I'm reaching out to seek your guidance regarding GitHub. As a newcomer to the platform, I find myself encountering challenges, particularly with regards to commits and pull requests. Specifically, I'm aiming to submit individual pull requests for each task I complete. However, I've noticed that when I make a commit while a pull request is open, the commit automatically becomes associated with that pull request.
> 
> I would greatly appreciate any insights or advice you could offer on how to address this issue.
> 
> Thank you for your time and assistance.
> 
> Warm regards,
> @SourabhRajput123

Hi, @SourabhRajput123
Thanks for reaching out with the question.
You have to make new branch for each task you are solving. At the moment you are making changes to the main branch so every commit goes into that. If you create new branch for each issue, the commits will go straight to the pull request where that branch is used. I can then merge your branch to the main from the pull request, which is the usual approach when using git in general. You can find instructions about the branch creating process in the Readme.

**Comment by SourabhRajput123** [comment]
> > Hello @nikohoffren,
> > I hope this message finds you well. I'm reaching out to seek your guidance regarding GitHub. As a newcomer to the platform, I find myself encountering challenges, particularly with regards to commits and pull requests. Specifically, I'm aiming to submit individual pull requests for each task I complete. However, I've noticed that when I make a commit while a pull request is open, the commit automatically becomes associated with that pull request.
> > I would greatly appreciate any insights or advice you could offer on how to address this issue.
> > Thank you for your time and assistance.
> > Warm regards,
> > @SourabhRajput123
> 
> Hi, @SourabhRajput123 Thanks for reaching out with the question. You have to make new branch for each task you are solving. At the moment you are making changes to the main branch so every commit goes into that. If you create new branch for each issue, the commits will go straight to the pull request where that branch is used. I can then merge your branch to the main from the pull request, which is the usual approach when using git in general. You can find instructions about the branch creating process in the Readme.

>Thank you so much, @nikohoffren, for your clear and detailed explanation. I really appreciate you taking the time to guide me through the process. Your instructions make perfect sense, and I'll be sure to follow them moving forward. I'll create a new branch for each task as per your suggestion, ensuring that my commits are properly organized within the corresponding pull requests. Your assistance has been immensely valuable, and I'm grateful for your support as I continue to learn and navigate GitHub. Thanks again for your help!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out our [forkcommitmerge.io](https://github.com/fork-commit-merge/fork-commit-merge-web) website repository. The repository contain real issues that you can help to resolve or create some of your own if you see any bugs or want to add new features to the site, etc. You can also check out the [Influences](https://github.com/fork-commit-merge/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Pull request merged**
