### PR TITLE
making the traffic lights

### PR DESCRIPTION
**Pull request by M-n0ur**
## Pull Request Type

What kind of change does this PR introduce?

[ ] Solved an issue/task
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:

## What is the current behavior?

Issue Number: Medium Issue 2 (React.js) #1532

### CODE REVIEW

**Comment by M-n0ur** [comment]
I would like to be accepted  and waiting for your advice on my code thanks alots

**Comment by M-n0ur** [comment]
I have one question when I fork the repo I create a new branch but should I merge  it with the main branch before the pull request

**Review by nikohoffren — APPROVED** [review]

**Comment by nikohoffren** [comment]
> I have one question when I fork the repo I create a new branch but should I merge it with the main branch before the pull request

You should create the pull request from the new branch as you did, so everything is good here.

**Comment by nikohoffren** [comment]
> I would like to be accepted and waiting for your advice on my code thanks alots

Traffic light looks to be working as expected, nicely done! There is just small issue that after green light there is no light at any of the lights for a second before the red appears, but that's a minor issue.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by M-n0ur** [comment]
> pull request has been merged. The files have been reset for the next contributor.
> 
> ### What's next?

that true 
I thought it will be better to make 1 second all the lights is off 
DO U WANT ME TO FIX IT OR LEAVE IT

**Comment by nikohoffren** [comment]
> > pull request has been merged. The files have been reset for the next contributor.
> > ### What's next?
> 
> that is true I thought it will be better to make 1 second all the lights is off DO U WANT ME TO FIX IT OR LEAVE IT

This PR is already merged, it's fine.

**Pull request merged**
