### PR TITLE
issue fixed #1371 | Medium Issue 2 (CSS)

### LINKED ISSUE #1371: Fork, Commit, Merge - Medium Issue 2 (CSS)
# Fork, Commit, Merge - Medium Issue 2 (CSS)
## Create Fire Animation Using CSS
*Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. The actions-user bot will reset the file back to previous state for the next contributor after your commit is merged. So you can just simply start working with the issue right away!*

*Issue created by [Avtech04](https://github.com/Avtech04).*

### How to get started:
Navigate to the `tasks/css/medium/fire` directory from the root of the project.
Open `styles.css` file and start implementing your solution!

### Description:
Your task is to create a fire animation similar as in the video provided.

https://github.com/nikohoffren/fork-commit-merge/assets/82566656/821a9549-fa43-4772-84a5-5bd85239378b

In the directory, there are two files: `index.html` and `styles.css`. The `index.html` file contains all the necessary HTML for the fire animation. In `styles.css` there are some classes already filled for you, and some classes that are missing the styles.
Add all the necessary styles for these classes:
```css
.fire-right .main-fire {
  /* TODO: Add the necessary styles here */
}

.fire-right .particle-fire {
  /* TODO: Add the necessary styles here */
}

.fire-left .main-fire {
  /* TODO: Add the necessary styles here */
}

.fire-left .particle-fire {
  /* TODO: Add the necessary styles here */
}
```
*Note: You are only required to modify the `styles.css` file.*

### How to run:
If you are using VS Code and have for example Live Server extension, you can simply open `index.html` with the server and check how the animation looks. If it looks to be working as expected, you are ready to make a pull request!
If you do not have Live Server extension, you'll find information about installing and how to use it [here](https://www.donskytech.com/visual-studio-code-live-server/).

---

Check out [README.md](https://github.com/nikohoffren/fork-commit-merge/blob/main/README.md) for more instructions and how to make a pull request.

Feel free to ask any questions here if you have some problems!

#### Also, kindly give this project a star to enhance its visibility for new developers!

### PR DESCRIPTION
**Pull request by nitinya9av**
## Pull Request Type

What kind of change does this PR introduce?

- Solved an issue/task

## What is the current behavior?

Issue Number: https://github.com/fork-commit-merge/fork-commit-merge/issues/1371

## What is the new behavior?

- a fire animation

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
The animation looks exactly same as before the changes, so i don't think the styles are quite right.

**Comment by nitinya9av** [comment]
fixed

**Review by nikohoffren — APPROVED** [review]
Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out our [forkcommitmerge.io](https://github.com/fork-commit-merge/fork-commit-merge-web) website repository. The repository contain real issues that you can help to resolve or create some of your own if you see any bugs or want to add new features to the site, etc. You can also check out the [Influences](https://github.com/fork-commit-merge/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Pull request merged**
